spring.datasource.url=jdbc:h2:mem:authdb
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# JWT ? sua chave secreta (mínimo 256 bits para HS256)
jwt.secret=minha-chave-super-secreta-que-precisa-ter-pelo-menos-256bits-ok
jwt.expiration=86400000
server.port=8081